config/routes.rb
OpenProject::Application.routes.draw do
  resources :companies do
    member do
      get :filter_available_members
      get :filter_available_projects

      post 'delete_member/:member_id', to: 'companies#delete_member', as: 'delete_member'
      post :add_members

      post 'delete_project/:project_id', to: 'companies#delete_project', as: 'delete_project'
      post :add_projects
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :members, :class_name => 'User'
  has_and_belongs_to_many :projects
  has_one :logo,
          -> { where("#{Attachment.table_name}.description = 'logo'") },
          :class_name => "Attachment",
          :as => :container,
          :dependent => :destroy

  validates_presence_of :name, :identifier, :short_description
  validates_uniqueness_of :identifier
  validates_format_of :identifier, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/

  acts_as_customizable
  acts_as_attachable :view_permission => :view_companies

  after_save :attach_logo

  def to_param
    @to_param ||= identifier.to_s
  end

  def has_custom_values?
    custom_values.any?{ |c| c.value.present? }
  end

  def attachments_deletable?(user = User.current)
    return user.admin?
  end

  def attachments_visible?(user = User.current)
    true
  end

  def project
    nil
  end

  def logo=(logo_file)
    logo.destroy if logo
    @logo_file = logo_file
  end

  def logo_file_exists?
    logo && FileTest.exists?(logo.diskfile) && logo.image?
  end

  def all_projects
    if Setting.plugin_openproject_companies['auto_calculate_projects']
      pr = []
      self.members.each do |u|
        pr << u.project_ids
      end
      Project.find(pr.uniq, :order => 'name')
    else
      self.projects.sorted_alphabetically
    end
  end

  private

  def attach_logo
    if @logo_file
      attach_files("1" => {'file' => @logo_file, 'description' => 'logo'})

      attachments.each(&:save!)
    end
  end
end

app/models/company_custom_field.rb
class CompanyCustomField < CustomField
  def type_name
    :label_company_plural
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout "no_menu"

  before_action :require_admin, except: [:index, :show]
  before_action :get_company_by_identifier, except: [:index, :new, :create]
  before_action :get_members, only: [:edit, :update, :show]
  before_action :get_projects, only: [:edit, :update]
  before_action :get_settings

  helper :projects, :custom_fields

  def index
    @companies = Company.all.order(name: :asc)
    @custom_fields = CompanyCustomField.all.order(position: :asc)
  end

  def show
    @projects = @company.all_projects
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new company_attributes

    if @company.save
      render_attachment_warning_if_needed(@company)
      flash[:notice] = t(:notice_successful_create)

      redirect_to @company
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @company.update company_attributes
      render_attachment_warning_if_needed(@company)
      flash[:notice] = t(:notice_successful_update)

      redirect_to @company
    else
      render action: 'edit'
    end
  end

  def destroy
    @company.destroy
    flash[:notice] = t(:notice_company_deleted)

    redirect_to companies_url
  end

  def delete_member
    member = User.find(params[:member_id])
    @company.members.delete(member)

    flash[:notice] = t(:notice_company_member_deleted)

    redirect_to edit_company_path(id: @company.identifier)
  end

  def add_members
    member_ids = params[:member_ids]
    @company.member_ids += member_ids

    flash[:notice] = t(:notice_company_member_added)

    redirect_to edit_company_path(id: @company.identifier)
  end

  def filter_available_members
    @members = @company.members.sorted_alphabetically
    found = params[:q].blank? ? User.active : User.active.like(params[:q])
    @available_members = found.sorted_alphabetically.limit(100) - @members

    render partial: 'available_members'
  end

  def delete_project
    project = Project.find(params[:project_id])
    @company.projects.delete(project)

    flash[:notice] = t(:notice_company_project_deleted)

    redirect_to edit_company_path(id: @company.identifier)
  end

  def add_projects
    project_ids = params[:project_ids]
    @company.project_ids += project_ids

    flash[:notice] = t(:notice_company_project_added)

    redirect_to edit_company_path(id: @company.identifier)
  end

  def filter_available_projects
    @projects = @company.projects.sorted_alphabetically
    found = params[:q].blank? ? Project.active : Project.active.like(params[:q])
    @available_projects = found.sorted_alphabetically.limit(100) - @projects

    render partial: 'available_projects'
  end

  private

  def get_settings
    @settings = Setting.plugin_openproject_companies
  end

  def get_members
    @members = @company.members.sorted_alphabetically
    @available_members = User.active.sorted_alphabetically.limit(100) - @members
  end

  def get_projects
    @projects = @company.projects.sorted_alphabetically

    all_projects = Project.active.sorted_alphabetically.order(name: :asc).limit(100)
    @available_projects = all_projects - @projects
  end

  def get_company_by_identifier
    @company = Company.find_by!(identifier: params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def company_attributes
    custom_field_values = [params.require(:company)[:custom_field_values]]
      .reject(&:nil?)
      .map(&:permit!)
      .first

    params
      .require(:company)
      .permit(:name, :identifier, :short_description, :description, :url, :logo)
      .merge(custom_field_values: custom_field_values || {})
  end

  def default_breadcrumb
    ActionController::Base.helpers.link_to(t('label_company_plural'), companies_path)
  end

  def show_local_breadcrumb
    if action_name == 'index'
      false
    else
      true
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def logo_of(company)
    if company.logo_file_exists?
      url = logo_url(company.logo)
      if company.url.present?
        link_to(image_tag(url), company.url)
      else
        image_tag(url)
      end
    end
  end

  def companies_check_box_tags(name, items)
    s = []
    items.each do |item|
      s << "<label>#{ check_box_tag name, item.id, false } #{h item.name}</label><br/>\n"
    end
    s.join.html_safe
  end

  private

  def logo_url(logo)
    url_for( :only_path => false, :controller => 'attachments', :action => 'download', :id => logo, :filename => logo.filename )
  end
end

app/views/companies/_available_members.html.erb
<%= companies_check_box_tags('member_ids[]', @available_members) %>

app/views/companies/_available_projects.html.erb
<%= companies_check_box_tags('project_ids[]', @available_projects) %>

app/views/companies/_form.html.erb
<%= error_messages_for 'company' %>

<%= form_for @company, :builder => TabularFormBuilder, :html => {:multipart => true} do |f| %>

  <section class="form--section">
    <div class="form--field -required"><%= f.text_field :name, :required => true, container_class: '-wide' %></div>
    <div class="form--field -required"><%= f.text_field :identifier, :required => true, container_class: '-wide' %></div>
    <div class="form--field -required"><%= f.text_field :short_description, :required => true, container_class: '-wide' %></div>
    <div class="form--field"><%= f.text_area :description, container_class: '-wide' %></div>
    <div class="form--field"><%= f.text_field :url, container_class: '-wide' %></div>

    <% @company.custom_field_values.each do |value| %>
      <div class="form--field"><%= custom_field_tag_with_label :company, value %></div>
    <% end %>

    <fieldset class="form--fieldset">
      <legend class="form--fieldset-legend"><%= l(:field_logo) %></legend>
      <div class="form--field">
        <div class="attachment_field form--field-container">
          <div class="form--file-container">
            <%= f.file_field :logo, size: 30, id: nil, no_label: true %>
          </div>
        </div>
      </div>
      <%= logo_of(@company) %>
    </fieldset>
  </section>

  <%= styled_button_tag l(@company.new_record? ? :button_create : :button_save), class: '-highlight -with-icon icon-checkmark' %>

<% end %>

<% unless @company.new_record? %>

  <div style="clear: both;"></div>

  <div id="company-projects">
    <%= render :partial => 'projects' %>
  </div>

  <div id="company-members">
    <%= render :partial => 'members' %>
  </div>

<% end %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'companies/companies', plugin: :openproject_companies %>
<% end %>

app/views/companies/_members.html.erb
<div class="grid-block -no-outer-padding">
  <div class="grid-content medium-6 small-6">
    <% if @members.any? %>
      <fieldset class="form--fieldset">
        <legend class="form--fieldset-legend"><%= l(:label_member_plural) %></legend>
        <div class="generic-table--container">
          <div class="generic-table--results-container">
            <table class="generic-table list members">
              <tbody>
                <% @members.each do |member| %>
                  <% next if member.new_record? %>
                  <tr id="member-<%= member.id %>" class="member">
                    <td class="member -no-padding-left"><%= link_to_user member %></td>
                    <td class="buttons">
                      <%=
                        link_to "",
                                delete_member_company_path(id: @company, member_id: member.id),
                                method: :post,
                                title: t(:button_delete),
                                class: 'icon icon-delete'
                      %>
                    </td>
                  </tr>
                <% end; reset_cycle %>
              </tbody>
            </table>
          </div>
        </div>
      </fieldset>
    <% else %>
        <%= no_results_box custom_title: t(:notice_no_users) %>
    <% end %>
  </div>

  <div class="grid-content medium-6 small-6">
    <% if @available_members.any? %>
      <%=
        form_for(
          :member,
          url: { :controller => 'companies', :action => 'add_members', :id => @company },
          update: :members,
          method: :post
        ) do |f|
      %>
        <fieldset class="form--fieldset">
          <legend class="form--fieldset-legend"><%= l(:label_member_new) %></legend>

          <p><%= label_tag "member_search", l(:label_member_filter), :class => 'filter_label' %>
          <%= text_field_tag 'member_search', nil %></p>
          <%#= observe_field( :member_search, :method => :get, :frequency => 0.5, :update => :available_members, :url => {:action => "filter_available_members", :controller=>"companies" , :id => @company }, :with => "q" ) %>
          <div id="available_members" class="filtered_results">
            <%= render :partial => 'available_members' %>
          </div>

          <%= styled_button_tag t(:button_add), class: '-highlight -with-icon icon-checkmark' %>
        </fieldset>
      <% end %>
    <% end %>
  </div>
</div>

app/views/companies/_projects.html.erb
<% if @settings['auto_calculate_projects'] %>
  <p><%= t(:notice_auto_calculate_projects) %></p>
<% else %>
  <div class="grid-block -no-outer-padding">
    <div class="grid-content medium-6 small-6">
      <% if @projects.any? %>
        <fieldset class="form--fieldset">
          <legend class="form--fieldset-legend"><%= t(:label_project_plural) %></legend>
          <div class="generic-table--container">
            <div class="generic-table--results-container">
              <table class="generic-table list projects">
                <tbody>
                  <% @projects.each do |project| %>
                    <% next if project.new_record? %>
                    <tr id="project-<%= project.id %>" class="project">
                      <td class="project -no-padding-left"><%= link_to_project project %></td>
                      <td class="buttons">
                        <%=
                          link_to "",
                                  delete_project_company_path(id: @company, project_id: project.id),
                                  method: :post,
                                  title: t(:button_delete),
                                  class: 'icon icon-delete'
                        %>
                      </td>
                    </tr>
                  <% end; reset_cycle %>
                </tbody>
              </table>
            </div>
          </div>
        </fieldset>
      <% else %>
        <%= no_results_box custom_title: t(:notice_no_project) %>
      <% end %>
    </div>

    <div class="grid-content medium-6 small-6">
      <% if @available_projects.any? %>
        <%=
          form_for(
            :project,
            url: { controller: 'companies', action: 'add_projects', id: @company },
            update: 'projects',
            method: :post
          ) do |f|
        %>
          <fieldset class="form--fieldset">
            <legend class="form--fieldset-legend"><%= t(:label_project_new) %></legend>

            <p><%= label_tag "project_search", l(:label_project_filter), :class => 'filter_label' %>
            <%= text_field_tag 'project_search', nil %></p>
            <%#= observe_field( :project_search, :method => :get, :frequency => 0.5, :update => :available_projects, :url => {:action => "filter_available_projects", :controller=>"companies" , :id => @company }, :with => "q" ) %>
            <div id="available_projects" class="filtered_results">
              <%= render :partial => 'available_projects' %>
            </div>

            <%= styled_button_tag t(:button_add), class: '-highlight -with-icon icon-checkmark' %>
          </fieldset>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= javascript_include_tag "companies/companies", plugin: :openproject_companies_plugin %>

<% breadcrumb_paths(default_breadcrumb, @company.name) %>
<%= toolbar title: @company.name %>

<%= render :partial => 'form' %>

<% html_title "#{t(:label_company_plural)} - #{@company.name}" %>

app/views/companies/index.html.erb
<% html_title t(:label_company_plural) -%>
<%= toolbar title: t(:label_company_plural) do %>
  <% if User.current.allowed_to?(:add_company, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_company_path,
          { class: 'button -alt-highlight',
            aria: {label: t(:label_user_new)},
            title: t(:label_company_new)} do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t('activerecord.models.Company') %></span>
      <% end %>
    </li>
  <% end %>
  <%= call_hook(:company_admin_action_menu) %>
<% end %>

<%= format_text @settings[:top_text] %>

<div class="generic-table--container">
  <div class="generic-table--results-container">
    <table class="generic-table">
      <colgroup>
        <% (1..(5 + @custom_fields.size)).each do |_| %>
          <col highlight-col>
        <% end %>
      </colgroup>
      <thead>
        <tr>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Company.human_attribute_name :name %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Company.human_attribute_name :description %>
              </div>
            </div>
          </th>

          <% @custom_fields.each do |custom_value| %>
            <th>
              <div class="generic-table--header-outer">
                <div class="generic-table--header">
                  <%= custom_value.name %>
                </div>
              </div>
            </th>
          <% end %>

          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= t(:label_project_plural) %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= t(:label_member_plural) %>
              </div>
            </div>
          </th>

          <% if User.current.allowed_to?(:edit_company, nil, :global => true) %>
            <th>
              <div class="generic-table--empty-header"></div>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td class="name center"><%= link_to company.name, company %></td>
            <td><%= company.short_description %></td>
            <% @custom_fields.each do |custom_value| %>
              <td class="center">
                <%=h show_value(company.custom_value_for(custom_value)) %>
              </th>
            <% end %>
            <td class="center"><%= company.all_projects.count %></td>
            <td class="center"><%= company.members.count %></td>
            <% if User.current.allowed_to?(:edit_company, nil, :global => true) %>
              <td class="buttons">
                <%= link_to "", edit_company_path(company), class: 'icon icon-edit' %>
                <%=
                  link_to(
                    "",
                    company,
                    method: :delete,
                    class: 'icon icon-delete',
                    data: { confirm: t(:text_are_you_sure) }
                  )
                %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<p>
  <%= format_text @settings[:bottom_text] %>
</p>

app/views/companies/new.html.erb
<% breadcrumb_paths(default_breadcrumb, t(:label_company_new)) %>
<%= toolbar title: t(:label_company_new) %>

<%= render :partial => 'form' %>

<% html_title t(:label_company_new) %>

app/views/companies/show.html.erb
<% html_title "#{t(:label_company)} - #{@company.name}" %>
<% breadcrumb_paths(default_breadcrumb, @company.name) %>

<%= toolbar title: @company.name do %>
  <% if User.current.allowed_to?(:edit_company, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to edit_company_path(@company), :class => 'button' do %>
        <%= op_icon('button--icon icon-edit') %>
        <span class="button--text"><%= t(:label_edit) %></span>
      <% end %>
    </li>
  <% end %>
  <% if User.current.allowed_to?(:add_company, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_company_path, :class => 'button -alt-highlight' do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t(:label_company)  %></span>
      <% end %>
    </li>
  <% end %>
<% end %>

<h3><%= @company.short_description %></h3>

<div class="grid-block -no-outer-padding">
  <div id="company-description" class="grid-content">
    <% if @company.url.present? %>
      <p><%= link_to @company.url, @company.url, :class => "external" %></p>
    <% end %>

    <%= logo_of(@company) %>

    <%= format_text @company.description %>

    <% if @company.has_custom_values? %>
      <% @company.custom_values.each do |custom_value| %>
        <div class="form--field">
            <label class="form--label">
              <b><%= custom_value.custom_field.name %></b>
            </label>
            <span class="form--field-container">
              <%= show_value(custom_value) %>
            </span>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="company-relations" class="grid-content widget-boxes">
    <% if @projects.any? %>
      <div class="projects widget-box">
        <h3 class="widget-box--header">
          <%= op_icon('icon-context icon-projects') %>
          <span class="widget-box--header-title"><%= t(:label_project_plural) %></span>
        </h3>
        <%= render_project_list @projects %>
      </div>
    <% end %>
    <% if @members.any? %>
      <div class="members widget-box">
        <h3 class="widget-box--header">
          <%= op_icon('icon-context icon-group') %>
          <span class="widget-box--header-title"><%= t(:label_member_plural) %></span>
        </h3>
        <ul>
          <% @members.each do |member| %>
            <li><%= link_to member.name, member %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'companies/companies', plugin: 'openproject_companies' %>
<% end %>

app/views/projects/_companies.html.erb
<% if @project.companies.size >= 1 %>
  <h3><%= t(:label_company_plural) %></h3>
  <ul>
    <% @project.all_companies.each do |company| %>
      <li><%= link_to company.name, company %></li>
    <% end %>
  </ul>
<% end %>

app/views/settings/_companies.html.erb
<% html_title "#{t(:label_administration)} - #{t(:label_company_plural)}" %>

<p><%= t(:label_companies_settings_projects) %></p>

<div class="form--field">
  <label class="form--label" for="settings_auto_calculate_projects">
    <%= t(:field_auto_calculate_projects) %>
  </label>
  <%= styled_check_box_tag 'settings[auto_calculate_projects]', '1', @settings['auto_calculate_projects'] %>
</div>

<p><%= t(:label_companies_settings_intro) %></p>

<div class="form--field">
  <label class="form--label" for="settings_top_text"><%= t(:field_top_text) %></label>
  <span class="form--field-container">
    <span class="form--text-area-container">
      <%= text_area_tag 'settings[top_text]', @settings['top_text'], :rows => 5, :class => 'wiki-edit' %>
      <%= wikitoolbar_for 'settings_top_text' %>
    </span>
  </span>
</div>

<div class="form--field">
  <label class="form--label" for="settings_bottom_text"><%= t(:field_bottom_text) %></label>
  <span class="form--field-container">
    <span class="form--text-area-container">
      <%= text_area_tag 'settings[bottom_text]', @settings['bottom_text'], :rows => 5, :class => 'wiki-edit' %>
      <%= wikitoolbar_for 'settings_bottom_text' %>
    </span>
  </span>
</div>

<%= link_to t(:label_custom_field_plural), :controller => 'custom_fields', :action => 'index', :params => {:tab => 'CompanyCustomField'} %>
<p><%= t(:notice_save_before_clicking) %></p>

app/views/users/_companies.html.erb
<% if @user.companies.size >= 1 %>
  <h3><%= t(:label_company_plural) %></h3>
  <ul>
    <% @user.companies.all.order(name: :asc).each do |company| %>
      <li><%= link_to company.name, company %></li>
    <% end %>
  </ul>
<% end %>